#!/usr/bin/env bash
set -o nounset -o errexit
export PATH=/usr/sbin:/usr/bin:$PATH
#echo $(ip addr show eth0 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
echo "$(ip -f inet -o a | tr -s \  | awk '!/: (lo|docker)/{print $4}' | cut -f1 -d/ | head -1)"
